 ---------------------------------------------
DROP TABLE #ASESOR_ORIGINADOR;

CREATE LOCAL TEMPORARY TABLE #ASESOR_ORIGINADOR AS (
SELECT 
CONTRACT_ID,
ASESOR_ORIGINADOR
FROM 
(
SELECT
CONTRACT_ID,
ADVISOR_ID AS ASESOR_ORIGINADOR,
ROW_NUMBER() OVER (PARTITION BY CONTRACT_ID ORDER BY CONTRACT_ATOMIC_START_DT  ASC) AS REG
FROM DP_SEM_EXP.CONTRACT_HEADER_ATOMIC_HIST 
WHERE PRODUCT_ID = 30 AND CONTRACT_STATUS_CD = 1
) AS BASE
WHERE REG = 1
);

SELECT COUNT(*) FROM #ASESOR_ORIGINADOR;

 ---------------------------------------- ALTAS ASESORES MES ---------------------------

SET 'FECHA_INICIO' ='2024-12-01';
SET 'FECHA_FIN' ='2024-12-31';
DROP TABLE #COSECHA_ASESORES;
CREATE LOCAL TEMPORARY COLUMN TABLE #COSECHA_ASESORES AS (
SELECT DISTINCT 
EMPLOYEE_ID,
POSITION_DESC,
POSITION_START_DT,
EMPLOYEE_AGREEMENT_DT,
EMPLOYEE_FIRST_AGREEMENT_DT,
REPLACE(TO_VARCHAR(EMPLOYEE_FIRST_AGREEMENT_DT,'YYYY-MM'),'-','') AS COSECHA,
EMPLOYEE_STATUS_DESC,
EMPLOYEE_STATUS_START_DT 
FROM DP_SEM_EXP.DIM_EMPLOYEE_HIST 
WHERE POSITION_DESC = 'ASESOR CI' AND 
EMPLOYEE_FIRST_AGREEMENT_DT BETWEEN SESSION_CONTEXT('FECHA_INICIO') AND SESSION_CONTEXT('FECHA_FIN') AND POSITION_START_DT BETWEEN SESSION_CONTEXT('FECHA_INICIO') AND SESSION_CONTEXT('FECHA_FIN') )
;

SELECT COSECHA, COUNT(*) FROM #COSECHA_ASESORES GROUP BY COSECHA;


-------------------------------------------------------------------------------- CREDITOS ACTIVOS AL CORTE 
 
SET 'FECHA_CORTE'='2025-05-31';
DROP TABLE #ACTIVOS_CORTE;
CREATE LOCAL TEMPORARY COLUMN TABLE #ACTIVOS_CORTE AS ( 
SELECT DISTINCT
CONTRACT_ID, 
ADVISOR_ID AS ASESOR_CORTE,
CONTRACT_STATUS_CD,
CONTRACT_START_DT,
SESSION_CONTEXT('FECHA_CORTE') AS CORTE 
FROM DP_SEM_EXP.CONTRACT_HEADER_ATOMIC_HIST AS C 
WHERE PRODUCT_ID=30 AND C.CONTRACT_STATUS_CD IN (1,28) 
AND SESSION_CONTEXT('FECHA_CORTE') between C.CONTRACT_ATOMIC_START_DT AND COALESCE(C.CONTRACT_ATOMIC_END_DT,
CAST('9999-01-01' AS date)) 
);

---SELECT COUNT(DISTINCT CONTRACT_ID) FROM #ACTIVOS_CORTE WHERE ASESOR_CORTE = 86176238;


------------------------------------ --------------- JOIN

DROP TABLE #CONTRATOS_CORTE;
CREATE LOCAL TEMPORARY TABLE #CONTRATOS_CORTE AS (
SELECT 
AC.CONTRACT_ID,
CA.EMPLOYEE_ID,
AC.ASESOR_CORTE,
AO.ASESOR_ORIGINADOR,
AC.CONTRACT_STATUS_CD,
CA.POSITION_DESC,
AC.CONTRACT_START_DT,
CA.POSITION_START_DT,
CA.EMPLOYEE_AGREEMENT_DT,
CA.EMPLOYEE_FIRST_AGREEMENT_DT,
CA.COSECHA,
AC.CORTE,
CA.EMPLOYEE_STATUS_DESC,
CA.EMPLOYEE_STATUS_START_DT 
FROM #COSECHA_ASESORES AS CA
INNER JOIN #ACTIVOS_CORTE AS AC ON CA.EMPLOYEE_ID = AC.ASESOR_CORTE
INNER JOIN #ASESOR_ORIGINADOR  AS AO ON AC.CONTRACT_ID = AO.CONTRACT_ID
---WHERE CA.EMPLOYEE_ID = 86176238
ORDER BY AO.ASESOR_ORIGINADOR
)
;
------------------VALIDADOR------------
/*
SELECT 
CONTRACT_ID, 
ADVISOR_ID,
CONTRACT_START_DT,
CONTRACT_STATUS_START_DT,
CONTRACT_STATUS_CD,
CONTRACT_ATOMIC_START_DT,
CONTRACT_ATOMIC_END_DT,
PRODUCT_ID
FROM DP_SEM_EXP.CONTRACT_HEADER_ATOMIC_HIST 
WHERE CONTRACT_ID in (125197599, 122639983, 118831787)   
ORDER BY CONTRACT_ID, CONTRACT_STATUS_START_DT, CONTRACT_ATOMIC_START_DT;

SELECT COUNT(*) FROM #CONTRATOS_CORTE
*/
----------------

----DROP TABLE ASESORES;
---TRUNCATE TABLE ASESORES;
---CREATE COLUMN TABLE ASESORES AS(
INSERT INTO ASESORES(
SELECT
CC.CONTRACT_ID,
CC.EMPLOYEE_ID,
CC.ASESOR_CORTE,
CC.ASESOR_ORIGINADOR,
CASE WHEN CC.ASESOR_ORIGINADOR = CC.ASESOR_CORTE THEN 0 ELSE 1 END AS ORIGEN_TRASPASO,
CC.CONTRACT_STATUS_CD,
CC.POSITION_DESC,
CC.CONTRACT_START_DT,
CC.POSITION_START_DT,
CC.EMPLOYEE_AGREEMENT_DT,
CC.EMPLOYEE_FIRST_AGREEMENT_DT,
CC.COSECHA,
CC.EMPLOYEE_STATUS_DESC,
CC.EMPLOYEE_STATUS_START_DT,
CBH.CONTRACT_BAL_START_DT,
CBH.CONTRACT_BAL_END_DT,
CBH.BAL_CAPITAL_AMT AS MONTO_CARTERA,
SESSION_CONTEXT('FECHA_CORTE') AS CORTE,
CASE WHEN COALESCE(DAYS_BETWEEN(CBH.PAST_DUE_DT,SESSION_CONTEXT('FECHA_CORTE')),0)<=0 THEN 0 ELSE COALESCE(DAYS_BETWEEN(CBH.PAST_DUE_DT,SESSION_CONTEXT('FECHA_CORTE')),0) END AS DIAS_ATRASO_ACTUAL
FROM DP_SEM_EXP.FACT_CONTRACT_BALANCE_HIST AS CBH
INNER JOIN #CONTRATOS_CORTE AS CC ON CBH.CONTRACT_ID = CC.CONTRACT_ID --AND SESSION_CONTEXT('FECHA_CORTE') BETWEEN O.CONTRACT_ATOMIC_START_DT AND  COALESCE(O.CONTRACT_ATOMIC_END_DT, CAST('9999-01-01' AS date))
WHERE SESSION_CONTEXT('FECHA_CORTE') BETWEEN CONTRACT_BAL_START_DT AND  COALESCE(CONTRACT_BAL_END_DT, CAST('9999-01-01' AS date))
);


---------------VALIDA
---SELECT * FROM ASESORES WHERE EMPLOYEE_ID = 86176238;

SELECT CORTE, COUNT(*) FROM ASESORES
GROUP BY CORTE;

--DELETE FROM ASESORES WHERE CORTE IN ('2025-07-31','2025-08-31')

